FROM node:16-alpine
WORKDIR /usr/src/kittychan_events
COPY package.json .
RUN npm install -g typescript cpx

ARG KITTY_CHAN_TOKEN
ENV KITTY_CHAN_TOKEN $KITTY_CHAN_TOKEN

ARG KITTY_CHAN_ID
ENV KITTY_CHAN_ID $KITTY_CHAN_ID

ARG KITTY_CHAN_GRPC_URL
ENV KITTY_CHAN_GRPC_URL $KITTY_CHAN_GRPC_URL

ARG REDIS_HOST
ENV REDIS_HOST $REDIS_HOST

ARG REDIS_PASS
ENV REDIS_PASS $REDIS_PASS

RUN npm install
COPY . .
RUN tsc
RUN npm run build:proto
CMD ["node", "./dist/main.js"]