version: "3.9"
services:
  kittychan:
    build: .
    image: kittychan-events
    container_name: kittychan-events
    networks:
      - kittychan-network
    restart: always
  
networks:
  kittychan-network:
    name: kittychan-network