name: kitty chan Events Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg KITTY_CHAN_TOKEN=${{ secrets.KITTY_CHAN_TOKEN }} \
            --build-arg KITTY_CHAN_ID=${{ vars.KITTY_CHAN_ID }} \
            --build-arg KITTY_CHAN_GRPC_URL=${{ vars.KITTY_CHAN_GRPC_URL }} \
            --build-arg REDIS_HOST=${{ vars.REDIS_HOST }} \
            --build-arg REDIS_PASS=${{ vars.REDIS_PASS }} \
            -t jagalive/kittychan-events:${{ github.sha }} .
          docker tag jagalive/kittychan-events:${{ github.sha }} jagalive/kittychan-events:latest
        working-directory: ./

      - name: Push Docker image
        run: |
          docker push jagalive/kittychan-events:${{ github.sha }}
          docker push jagalive/kittychan-events:latest
